import zmq
import json
import base64
import io
from flask import Flask, send_file, render_template, request, jsonify, redirect, url_for

import requests
from utils.bookmark import BookmarkManager


app = Flask(__name__)


# We use this to store queries results to avoid spamming the JPL servers with a ton of requets
search_cache = {}

bookmark_manager = BookmarkManager()

# Routes for Bookmarking

@app.route("/bookmark/add/<name>")
def add_bookmark(name):
    bookmark_manager.add_bookmark(name)
    return jsonify({"status": "success", "name": name})

@app.route("/bookmark/remove/<name>")
def remove_bookmark(name):
    bookmark_manager.remove_bookmark(name)
    return jsonify({"status": "success", "name": name})

@app.route("/bookmarks")
def get_bookmarks():
    return jsonify(bookmark_manager.list_bookmarks())

# Routes for my solar system viwer
@app.route('/')
def splash():
    return render_template('index.html')

@app.route('/search')
def search_page():
    return render_template('search.html')

@app.route('/bookmarksManager')
def bookmarks_page():
    bookmarks = bookmark_manager.load_bookmarks()
    
    return render_template("bookmarksManager.html", bookmarks=bookmarks)
   

@app.route('/object/<name>')
def object_page(name):
    print("test" + name)
    # Most of my data is directly from JPL and their amazing open source APIs
    api_url = f"https://ssd-api.jpl.nasa.gov/sbdb.api?sstr={name}"
    try:
        obj = search_cache.get(name)
        print(obj)
    except Exception as e:
        print("API error:", e)
        obj = {}

    return render_template('object.html', obj=obj)

### MICROSERVICES

PDF_SERVER = "tcp://localhost:8091"
MATH_SERVER = "tcp://localhost:8094"


def send_zmq_request(server_addr, request_dict):
    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.connect(server_addr)
    socket.send_json(request_dict)
    response = socket.recv_json()
    socket.close()
    context.term()
    return response

# This is the main function that handles the generate PDF report button
@app.route("/object/<name>/pdf")
def pdf_service(name):
    obj = search_cache.get(name)
    if not obj:
        return f"No data found for {name}", 404

    # Prepare orbital parameters as a text block
    orbit_text = ""
    if obj.get("orbit") and obj["orbit"].get("elements"):
        for el in obj["orbit"]["elements"]:
            units = f" {el['units']}" if el.get("units") else ""
            orbit_text += f"{el['title']}: {el['value']}{units}\n"
    else:
        orbit_text = "No orbital data available."

    # Construct PDF request
    pdf_request = {
        "module": "pdf_report",
        "function": "report",
        "args": {
            "title": f"{obj['object']['fullname']} Report",
            "sections": {
                "Summary": f"Report for {obj['object']['fullname']}",
                "Orbital Parameters": orbit_text,
                "Notes": "Generated by Solar System Explorer"
            }
        }
    }

    # Send request to microservice
    resp = send_zmq_request(PDF_SERVER, pdf_request)
    b64_pdf = resp["result"]
    pdf_bytes = base64.b64decode(b64_pdf)

    return send_file(
        io.BytesIO(pdf_bytes),
        mimetype="application/pdf",
        as_attachment=True,
        download_name=f"{obj['object']['fullname']}_report.pdf"
    )


@app.route("/convert_au", methods=["POST"])
def convert_au():
    data = request.json
    value = float(data["value"])

   
    request_obj = {
        "module": "astronomy",
        "function": "au_to_km",
        "args": { "value": value }
    }

    resp = send_zmq_request(MATH_SERVER, request_obj)
    km_value = resp["result"]

    return jsonify({"value": km_value})


#END



# In the future maybe move this to another page!
@app.route("/results")
def results_page():
    query = request.args.get("q", "")
    results = []

    if query:
        url = f"https://ssd-api.jpl.nasa.gov/sbdb.api?sstr={query}"
        try:
            resp = requests.get(url, timeout=5)
            resp.raise_for_status()
            data = resp.json()
            
            
            if 'object' in data:
                obj = data['object']

                search_cache[data['object']['fullname']] = data
                print(search_cache[data['object']['fullname']])
                results.append({
                    "name": obj.get("fullname", obj.get("des", query)),
                    "designation": obj.get("des", ""),
                    "type": obj.get("orbit_class", ""),
                    "discovery": obj.get("discovery_date", ""),
                })
                
            # Satellites (if available)
            if 'satellites' in data:
                for sat in data['satellites']:
                    results.append({
                        "name": sat.get("name", sat.get("des", "Unknown")),
                        "designation": sat.get("des", ""),
                        "type": "Satellite",
                        "discovery": sat.get("discovery_date", ""),
                    })

        except Exception as e:
            print("API error:", e)
            results = []

    return render_template("results.html", query=query, results=results)



if __name__ == '__main__':
    app.run(debug=True)
